name: Docker 
on:
  push:
    branches: 
      - development
env: 
   version: '0.0.1'     
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - 
      name: test
      run: echo "${{ secrets.DOCKER_USERNAME }}/umbrel:$version"
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/umbrel:$version
